### ISSUE TITLE
Theme not showing up correctly

### ISSUE THREAD

**Issue by bantya** [meetio-theme/sublime-meetio-theme#1]
After a lot of time, some robust and elegant looking theme is in the market now. **Meetio** seems to have immense potential to be the next **Material Theme**, but there are some hiccups:

I installed Meetio twice:
1. Manual **.zip** installation 
2. Using Sublime **PackageControl: Add Repository** 

⭕ For first one, the **Activate** command wasn't showing up, just the **Meetio: Edit Settings** showed.
Also for `Preferences → Package Settings → Meetio`, both settings except **Edit Settings** were grayed out.

I can say that this installation method was not a good bet for me.

⭕ For second one, everything seems to be normal. I could see the **Meetio: Activate** command and upon execution saw something like:

![image](https://user-images.githubusercontent.com/16685565/51184925-ba1f9280-18fb-11e9-9d6c-cab38c84f5ba.png)

No matter what theme is activated, the orange rectangles show up all the time.

⭕ The status-bar stayed **AS IS** for all 4 themes. It does not change color according to the different theme selected.

⭕ Upon clicking on **Meetio: Edit Settings** in above mentioned cases, 

![image](https://user-images.githubusercontent.com/16685565/51186185-10da9b80-18ff-11e9-8f98-08488db2ec2f.png)

this showed up.

⭕ The **Changelog** menu as shown below does nothing.

![image](https://user-images.githubusercontent.com/16685565/51186267-43849400-18ff-11e9-827d-198eaacc0c7b.png)

👍🏼 All the best for next steps buddy. 

(This is my first time opening a first issue.)

**Comment by mauroreisvieira** [comment]
@bantya thanks for your feedback. I don't have way to test Meetio in Window and is very nice for me to have this comments, help me to make this theme more power full in all Operating Systems.
I build this Theme for all Sublime Text user!

Package Control install its in my list during this week I go make the PR to Package Control repository. 
About the issue, I forgot to indicate in Readme file when in close/download the Meetio theme you need rename the folder to **Meetio** instead of **meetio**. Please can you try rename the folder.

Thanks again for you feedback! 
👍

**Comment by bantya** [comment]
Ask for any help needed. 

Just installed the updated theme. Now, it looks something like:

Just installed updated theme
![image](https://user-images.githubusercontent.com/16685565/51403955-0d057e00-1b78-11e9-8b7f-9d4c29b288a6.png)

**Comment by mauroreisvieira** [comment]
Hu @bantya you rename the folder?

**Comment by bantya** [comment]
Yes.

**Comment by pedroladeira** [comment]
Hello.
I have the same problem, and you can see a pick of my command line, with some errors when I change the theme.

Nice theme. Great work 

![sublime_error](https://user-images.githubusercontent.com/4301649/51463595-7e515680-1d5b-11e9-8c93-e646bb54ea87.JPG)

**Comment by pedroladeira** [comment]
Hello,

I already fix the problem, just assert the path of the theme in package control. 
I had the package in the **"..\AppData\Roaming\Sublime Text 3\Packages\Meetio\meetio-master\"** path instead of **"..\AppData\Roaming\Sublime Text 3\Packages\Meetio"**

Thanks, once again

**Comment by mauroreisvieira** [comment]
Thanks @pedroladeira. I guess when Meetio go to Package Control this problem disappear.

**Comment by mauroreisvieira** [comment]
@bantya think that close this question. I do not find any way to fix this problem on my side. I think when this theme is in package control, the problem maybe solved.

**Comment by bantya** [comment]
Good to hear and thanks again for the theme. 🙂
