### ISSUE TITLE
no such prop layer.tint when matching overlay_control against overlay_control

### ISSUE THREAD

**Issue by nicksspirit** [meetio-theme/sublime-meetio-theme#10]
Whenever I use the keyboard shortcut for access the command pallete, I keep on getting this message being logged into the sublime console.

`no such prop layer.tint when matching overlay_control against overlay_control`

**Comment by nicksspirit** [comment]
Actually I noticed that it also gets logged as I hover over the elements in the command pallete too

**Comment by mauroreisvieira** [comment]
Hi @OdinTech3 I will check this. Ty for you feedback.

**Comment by mauroreisvieira** [comment]
Hi @OdinTech3 issue solved in [version 2.0.1](https://github.com/mauroreisvieira/meetio/releases/tag/2.0.1)
