### ISSUE TITLE
Drawing issues - mulitple files stay selected

### ISSUE THREAD

**Issue by f8ttyc8t** [meetio-theme/sublime-meetio-theme#11]
I'm using latest version of both Sublime Text (3.2.1 Build 3207) as well as lates Meetio theme being available using package control. 

And I'm loving Meetio, it's supreme - thanks for crafting it!

Unfortunately:
Most of time, using Meetio-Lighter color scheme (having Meetio theme selected too)  is causing multiple items of side bar are drawn as if being selected. Please see items marked using a "red dot" in screenshot attached.

Note: this does not happen when using Meetio-Darker color scheme.

![Meetio-drawin-glitches](https://user-images.githubusercontent.com/1023438/57605143-44080100-7566-11e9-8ee9-f26afcd72bb4.png)

Any ideas about this?

**Comment by mauroreisvieira** [comment]
Hi @f8ttyc8t thanks for your feedback, is very important for me. I will check this issue. 

TY

**Comment by f8ttyc8t** [comment]
Thanks in advance!

**Comment by mauroreisvieira** [comment]
Hi @f8ttyc8t I can't reproduz the error, is very stange is only appear on Meetio Lighter, because this issue, is related with the theme not the scheme, but the theme is the same for all scheme variations its only adaptes. 
But I will continue to search for this bug and fix this. 

only to keep you aligned.

**Comment by f8ttyc8t** [comment]
@mauroreisvieira thanks for investigating it!

I think it's related to using SolarizeToggle package.
As soon I install and use it, light schema is causing these glitches.

Easy to reproduce - use user settings for SolarizeToggle package:

``` JSON
{
	"color_scheme_dark": "Packages/Meetio/schemes/Meetio-Darker.sublime-color-scheme",
	"color_scheme_light": "Packages/Meetio/schemes/Meetio-Lighter.sublime-color-scheme",
	"enable_font_switching": false,
	"enable_theme_switching": true,
	"solarized_toggle_mode": "light",
	"theme_dark": "Meetio.sublime-theme",
	"theme_light": "Meetio.sublime-theme"
}
``` 

(Too bad, because SolarizeToggle it's really a precious tool for me)

**Comment by mauroreisvieira** [comment]
@f8ttyc8t one question, why do you need this package to toggle your scheme?

**Comment by f8ttyc8t** [comment]
@mauroreisvieira I've mapped F12 to quick toggle theme/scheme.
So I'm able to adapt UI to fit my requirements based on environmental conditions (daylight/cloudy/sunny/night/...).
So I mainly need it/used it for convenience reasons.

**Comment by mauroreisvieira** [comment]
Ok. I will install this package and try to see the issue.

**Comment by f8ttyc8t** [comment]
@mauroreisvieira thanks! Really appreciate that!

**Comment by f8ttyc8t** [comment]
I've tried to reproduce it using fresh&clean SB installation.
Then I installed Meetio using package manager and activated light theme/color scheme.
GUI became disordered as soon SB window gets resized, moving mouse cursor over e.g. filenames fixes related regions.

![SB-messy-GUI](https://user-images.githubusercontent.com/1023438/57851430-d9aec500-77e0-11e9-9cf3-fc5ee4aa2b11.png)

**Comment by f8ttyc8t** [comment]
Need to correct my initial statement:
visual glitches not only occur in light but also in dark theme,
(Did not notice it earlier due to my monitor settings...)

Sorry for causing this!

**Comment by mauroreisvieira** [comment]
Hi again @f8ttyc8t your OS is window right?

**Comment by f8ttyc8t** [comment]
@mauroreisvieira thanks! Really appreciate you're still working on it!

Yes, I have this issue on multiple Windows-machines, each of them running Windows 10.

**Comment by mauroreisvieira** [comment]
Yes, in OSX I can't reproduce this issue, but during this week I will try in Windows OS.

**Comment by f8ttyc8t** [comment]
Confirming that: did not happen on neither Linux nor Mac.

**Comment by mauroreisvieira** [comment]
@f8ttyc8t yap. I will check.

**Comment by f8ttyc8t** [comment]
@mauroreisvieira  - did you find anything related to problem?
Would be cool to get this sorted out...

**Comment by mauroreisvieira** [comment]
Hi @f8ttyc8t sorry for this delay. But I don't have much time and a need to prepare the environment to fix this in a window machine.

**Comment by f8ttyc8t** [comment]
@mauroreisvieira thanks for still caring about it - really appreciate this!

Please let me know if you need some help.

**Comment by mauroreisvieira** [comment]
@pykong version [2.1.0](https://github.com/mauroreisvieira/meetio/releases/tag/2.1.0) is out!

Please check if the issue is solved! 

TY

**Comment by f8ttyc8t** [comment]
@mauroreisvieira Super - it seems to work!
Thank you very much for putting effort into this - will check a bit and come back later if there are still some glitches.

Thanks again for this fantastic package!

**Comment by mauroreisvieira** [comment]
TY!
