### ISSUE TITLE
ColorScheme - Style python type hints

### ISSUE THREAD

**Issue by pykong** [meetio-theme/sublime-meetio-theme#12]
@michaelblyons Thanks for putting up Meetio! It is an awesome theme + scheme collection.

With python [type hints](https://realpython.com/python-type-checking/), introduced with version `3.6`, becoming increasingly used any color scheme would profit from granting them special status.

**Consider this example:**
![image](https://user-images.githubusercontent.com/20211140/59210147-2ce02180-8bad-11e9-9c57-65e81d4d66a3.png)

Central is a long list of parameters and type hints. Here a visual differentiation between parameters and their associated type hints would greatly enhance the legibility of the code. For example, type hints might have a dark color and italics style.

Hence, it would be great if all color schemes that come with Meetio would be modified in this regard.

**Comment by michaelblyons** [comment]
I don't actually have anything to do with this theme. 😄 

Here's the text, for easier copypasta:

``` py
def copy(
    src_path: str,
    dst_path: str,
    data: Optional[dict] = None,
    *,
    exclude: Optional[List[str]] = None,
    include: Optional[List[str]] = None,
    pretend: bool = False,
    force: bool = False,
    skip: bool = False,
    quiet: bool = False,
) -> None:
    pass
```

It looks like it's _possible_ to support an alternative style for the annotations, but it would require Meetio to use a `meta` (namely `meta.function.parameters.annotation`) scope. It's not suggested practice for color schemes to do that.

If you'd like to do such a thing just for yourself, take a look at [this forum post](https://forum.sublimetext.com/t/reinstalling-st-at-current-version-while-keeping-packages/43768/5?u=michaelblyons).

**Comment by pykong** [comment]
Rules like those could serve as a starting point:

```json
    {
        "name":"[Py] Type hint",
        "scope":"meta.item-access.python,meta.function.parameters.annotation.python meta.qualified-name.python support.type.python, meta.function.annotation.return.python",
        "foreground":"color(grey alpha(0.7)))",
        "font_style":"italic"
    },
    {
        "name":"[Py] Type hint brackets",
        "scope":"source.python meta.function.parameters.annotation.python meta.item-access.python punctuation.section.brackets.begin.python, source.python meta.function.parameters.annotation.python meta.item-access.python punctuation.section.brackets.end.python",
        "foreground":"color(grey)",
        "font_style":"italic"
    }
```

**Comment by mauroreisvieira** [comment]
Hi @pykong, during this week I try to launch new version of Meetio with some bug fix and a Python syntax improves.

<img width="586" alt="Screenshot 2019-06-11 at 17 01 11" src="https://user-images.githubusercontent.com/3084774/59288032-bd306c00-8c6a-11e9-9db2-08b5ca8584e6.png">

any more suggestions?

**Comment by pykong** [comment]
@mauroreisvieira 

That coloring of the type hints looks awesome!
Looking forward to it! :)

Thanks!

**Comment by mauroreisvieira** [comment]
@pykong version [2.1.0](https://github.com/mauroreisvieira/meetio/releases/tag/2.1.0) is out!

**Comment by pykong** [comment]
That was fast. Thanks!

`Meetio-Cobalt` seems to be broken for me. It does not update.
 I am not sure about the reasons. Need to investigate.

The other Meetio color schemes work just fine.

**Comment by mauroreisvieira** [comment]
Hum... 

It's very strange... I will investigate..

<img width="1131" alt="Screenshot 2019-06-12 at 17 03 31" src="https://user-images.githubusercontent.com/3084774/59367517-2c25c780-8d34-11e9-8c55-6f46048016ab.png">
