### ISSUE TITLE
ColorScheme - Suggestions for other color schemes to adopt

### ISSUE THREAD

**Issue by pykong** [meetio-theme/sublime-meetio-theme#14]
I like how Meetio tune a variety of color schemes in a way to keep them distincitve but  yet make them recognizable as part of the "Meetio family". It is a work of a good designer.

Maybe other color scheme out there might make a great addition to the Meetio family as well.

Some candidates I deem worthy of this honor are:
- Seti
- Base16
- Mariana

**Comment by mauroreisvieira** [comment]
Hi @pykong yes, I had already thought about the Marian version, because I see lot of developers working with this scheme. 

TY for your feedback.

**Comment by mauroreisvieira** [comment]
Meetio-Mariana on next version...

<img width="780" alt="Screenshot 2019-06-17 at 18 18 19" src="https://user-images.githubusercontent.com/3084774/59623556-54466980-912c-11e9-82cc-07d9089693e5.png">

**Comment by pykong** [comment]
Looks awesome! Thanks for the teaser!

**Comment by mauroreisvieira** [comment]
Check new version.

**Comment by pykong** [comment]
The muted colors of your Marianna adaption are very pleasing to my eyes while being very functional.
