### ISSUE TITLE
Enhancement: Donor option?

### ISSUE THREAD

**Issue by pykong** [meetio-theme/sublime-meetio-theme#15]
I feel a great work as Meetio deserves to be supported.

Did I miss a donor link in the `README.md`?

If GitHub grants you a beta in the sponsor program you can also add a `FUNDING.yml`, to allow people to directly donate via GitHub:

![image](https://user-images.githubusercontent.com/20211140/59367936-6fd0ff00-8d3d-11e9-97d7-60a25773a4f8.png)

**Comment by mauroreisvieira** [comment]
Thanks @pykong.

Yes I thought about it, but I do not see the need for it anymore, I really like Sublime Text and I like developers to use ST, so it made Meetio Theme.

The idea of this theme is to follow the news of ST allowing an easy customization based on the taste of each one. 
Contrary to what happened with the Material Theme I do not have the idea to close a project, in the last case I pass the testimony to another person.

Anyone can contribute either with some PR or as a suggestion.

Again thank you very much and any problem or suggestion please contact me.

**Comment by pykong** [comment]
That is very honorable of you. Really great to see your enthusiasm for Sublime Text.
Keep on the good work. Looking forward to making Meetio even greater with you.
