### ISSUE TITLE
ColorScheme - Python name args coloring

### ISSUE THREAD

**Issue by pykong** [meetio-theme/sublime-meetio-theme#16]
Passing named arguments deserves some better coloring to **differentiate keyword and value**:

![image](https://user-images.githubusercontent.com/20211140/59375997-926c1380-8d4f-11e9-98ed-cd6f6239031a.png)

The declaration does a better job in this regard:

![image](https://user-images.githubusercontent.com/20211140/59376102-c5160c00-8d4f-11e9-9779-5e8de17ed0fd.png)

**Comment by mauroreisvieira** [comment]
TY, I will work on this.

**Comment by mauroreisvieira** [comment]
Hi @pykong 

<img width="288" alt="Screenshot 2019-06-17 at 18 15 39" src="https://user-images.githubusercontent.com/3084774/59623403-f7e34a00-912b-11e9-9c70-f35a6797158a.png">


on next version...

**Comment by pykong** [comment]
Much much more readable! Thanks. Looking forward to it!

**Comment by mauroreisvieira** [comment]
Check new version.

**Comment by pykong** [comment]
Looks absolutely stunning Thank You very much!
