### ISSUE TITLE
ColorScheme - Style all type hints

### ISSUE THREAD

**Issue by pykong** [meetio-theme/sublime-meetio-theme#18]
Addendum to #12 

Type hints can not only be part of a function's signature but actually any variable declaration.
Hence, it would be great if all type hints received the improved styling.

![image](https://user-images.githubusercontent.com/20211140/59707784-a1493f00-9203-11e9-8aac-ac23f45a5f0d.png)

**Comment by mauroreisvieira** [comment]
Check new version.

**Comment by pykong** [comment]
It looks great. Thank you!
