### ISSUE TITLE
ColorScheme - Make selections in mini map more visible

### ISSUE THREAD

**Issue by pykong** [meetio-theme/sublime-meetio-theme#19]
I like the selections in the minimap to stand out more.
Consider the following screenshot. Can you recognize which part of the text is currently selected? I can not (and there are definitely selections). Hence, this is a point of improvement.

![image](https://user-images.githubusercontent.com/20211140/59979458-881c0600-95e8-11e9-8ee7-cd0f60ae6310.png)

**Comment by pykong** [comment]
It would be also great to more visibly color other instances of the currently hovered word.

**Comment by mauroreisvieira** [comment]
Hi @pykong I can't change mini map, only the bacground of currently section selected.

**Comment by pykong** [comment]
@mauroreisvieira thanks for the fast feedback on this issue.
It is unfortunate that `Sublime Text` does not support a more fine-grained control for allowing us to address the minimap coloring separately.

Hence I am closing this for now.

**Comment by pykong** [comment]
I asked on the discord server about how to achieve this.
Indeed the response was negative. There currently does not seem a way to style the minimap differently from the text area.
