### ISSUE TITLE
Not Searchable in Sublime

### ISSUE THREAD

**Issue by zpreston123** [meetio-theme/sublime-meetio-theme#2]
Noticed this theme was released on Package Control today, but unable to search it in Sublime.

Not sure if this is a theme-related bug.

Looking forward to using it!

**Comment by mauroreisvieira** [comment]
Hi @zpreston123 its because you already have the theme in your Package folder. 
Please remove the Meetio folder inside your Package folder and search again in Package Control.

:)

**Comment by zpreston123** [comment]
@mauroreisvieira Just checked and it's not in my Packages folder.

**Comment by mauroreisvieira** [comment]
Hum :(

@zpreston123  what version of Sublime you have installed?

**Comment by zpreston123** [comment]
@mauroreisvieira Version 3.1.1, build 3176.

**Comment by mauroreisvieira** [comment]
@zpreston123 that's the problem, Meetio only works for versions **bigger than 3176**.

I'm already working on a version that is supported by older versions. 
The point is that the proposition of Meetio is to be as flexible as possible and can rewrite values of the variables in a simple way, but the versions lower to 3176 do **not support this possibility**.

**Comment by zpreston123** [comment]
@mauroreisvieira Installed the new Sublime stable build and searched this theme - found it!

Looks great, thank you!

**Comment by mauroreisvieira** [comment]
Thanks a lot @zpreston123
