### ISSUE TITLE
Enhancement - Custom Git Badges

### ISSUE THREAD

**Issue by pykong** [meetio-theme/sublime-meetio-theme#20]
What about adding custom git badges that are more descriptive than the default circle and chevron symbols Sublime Text offers.

See:
https://packagecontrol.io/packages/Git%20badges%20like%20VS%20Code

**Comment by mauroreisvieira** [comment]
It's a god idea. 

I will test that.

**Comment by mauroreisvieira** [comment]
Hi @pykong check new version [2.4.0](https://github.com/mauroreisvieira/meetio/releases/tag/2.4.0)

TY for your suggestion.

**Comment by pykong** [comment]
Looks aweseme and is so much more understandable than ST's default icons.
Keep on the good work!
