### ISSUE TITLE
How to change the space between the sidebar elements?

### ISSUE THREAD

**Issue by aronzillo** [meetio-theme/sublime-meetio-theme#21]
Currently the default theme shows the sidebar like this:

<img width="286" alt="Captura de Pantalla 2019-07-26 a la(s) 16 04 42" src="https://user-images.githubusercontent.com/12212275/61981528-8ebee400-afbf-11e9-9b3e-3d255a2ff02d.png">

But I would like it to be displayed this way

<img width="247" alt="Captura de Pantalla 2019-07-26 a la(s) 16 05 12" src="https://user-images.githubusercontent.com/12212275/61981564-a5653b00-afbf-11e9-8a16-ac88f98d563e.png">

Is there any way to do it?

**Comment by mauroreisvieira** [comment]
Hi @aronzillo ! Yes, it's possible. 

You can change anything in Meetio. 

Paste the fowling code in : **Meetio Theme: Configuration**
```    
{
    "rules": [
        {
            "class": "sidebar_tree",
            "indent": 20,
        }
    ]
}

```

But in the next release, you can change the `indent` directly in **variables**.

**Comment by aronzillo** [comment]
Thanks!
