### ISSUE TITLE
Is it possible to style the title bar of sublime in windows

### ISSUE THREAD

**Issue by nicksspirit** [meetio-theme/sublime-meetio-theme#22]
Is it possible to style the title bar of sublime text in windows, similar to this [windows 10 theme for sublime](https://packagecontrol.io/packages/Theme%20-%20Windows%2010)

**Comment by mauroreisvieira** [comment]
Hi @OdinTech3 sorry for the delay. I will check this ASAP.

**Comment by nicksspirit** [comment]
Great thanks! You are doing great work here so no rush.

**Comment by zpreston123** [comment]
@mauroreisvieira Any update on this?

**Comment by mauroreisvieira** [comment]
Hi @zpreston123 unfortunately ST not support custom colors in title bar.

**Comment by nicksspirit** [comment]
I see so do we close this issue for now @mauroreisvieira

**Comment by gz71422** [comment]
Start sublime and run python script
hide title bar

import win32gui
import win32api
import win32con
hwnd = win32gui.FindWindow('PX_WINDOW_CLASS',None)
style = win32api.GetWindowLong(hwnd, win32con.GWL_STYLE)
win32api.SetWindowLong(hwnd,win32con.GWL_STYLE,style & ~win32con.WS_BORDER & ~win32con.WS_THICKFRAME & ~win32con.WS_DLGFRAME)
win32gui.ShowWindow(hwnd,win32con.SW_MINIMIZE)
win32gui.ShowWindow(hwnd,win32con.SW_RESTORE)
