### ISSUE TITLE
Icons are missing/invalid - or my system isn't capable to handle them

### ISSUE THREAD

**Issue by f8ttyc8t** [meetio-theme/sublime-meetio-theme#25]
Hi!
Whenever I try to switch to Meetio theme (the latest ones, installed via "Meetion theme" by package manager), icons are missing/not shown.
Using recent Sublime Text Version (3.2.2, Build 3211) running on Windows 10, console shows errors below:

Unable to decode Packages/Meetio/assets/default/disclosure.png
Unable to decode Packages/Meetio/assets/default/disclosure_expanded.png
Unable to decode Packages/Meetio/assets/default/folder_closed.png
Unable to decode Packages/Meetio/assets/default/folder_open.png
Unable to decode Packages/Meetio/assets/default/arrow_folder_closed.png
Unable to decode Packages/Meetio/assets/default/arrow_folder_open.png
Unable to decode Packages/Meetio/assets/default/spinner11.png
Unable to decode Packages/Meetio/assets/default/spinner10.png
Unable to decode Packages/Meetio/assets/default/spinner9.png
Unable to decode Packages/Meetio/assets/default/spinner8.png
Unable to decode Packages/Meetio/assets/default/spinner7.png
Unable to decode Packages/Meetio/assets/default/spinner6.png
Unable to decode Packages/Meetio/assets/default/spinner5.png
Unable to decode Packages/Meetio/assets/default/spinner4.png
Unable to decode Packages/Meetio/assets/default/spinner3.png
Unable to decode Packages/Meetio/assets/default/spinner2.png
Unable to decode Packages/Meetio/assets/default/spinner1.png
Unable to decode Packages/Meetio/assets/default/spinner.png
Unable to decode Packages/Meetio/assets/default/folder_dup.png
Unable to decode Packages/Meetio/assets/default/icon_regex.png
Unable to decode Packages/Meetio/assets/default/icon_case_sensitive.png
Unable to decode Packages/Meetio/assets/default/icon_whole_word.png
Unable to decode Packages/Meetio/assets/default/icon_wrap.png
Unable to decode Packages/Meetio/assets/default/icon_in_selection.png
Unable to decode Packages/Meetio/assets/default/icon_highlight_matches.png
Unable to decode Packages/Meetio/assets/default/icon_preserve_case.png
Unable to decode Packages/Meetio/assets/default/icon_in_context.png
Unable to decode Packages/Meetio/assets/default/icon_use_buffer.png
Unable to decode Packages/Meetio/assets/default/arrow_right.png
Unable to decode Packages/Meetio/assets/default/arrow_down.png
Unable to decode Packages/Meetio/assets/default/icon_search.png
Unable to decode Packages/Meetio/assets/default/overflow_menu.png
Unable to decode Packages/Meetio/assets/default/icon_close.png
Unable to decode Packages/Meetio/assets/default/dirty_icon.png
Unable to decode Packages/Meetio/assets/default/overlay_bg.png
Unable to decode Packages/Meetio/assets/default/quick_panel_background.png
Unable to decode Packages/Meetio/assets/default/scroll_bar.png
Unable to decode Packages/Meetio/assets/default/scroll_puck.png
Unable to decode Packages/Meetio/assets/default/scroll_bar_horiz.png
Unable to decode Packages/Meetio/assets/default/scroll_puck_horiz.png
Unable to decode Packages/Meetio/assets/default/icon_branch.png
Unable to decode Packages/Meetio/assets/default/untracked.png
Unable to decode Packages/Meetio/assets/default/modified.png
Unable to decode Packages/Meetio/assets/default/added.png
Unable to decode Packages/Meetio/assets/default/staged.png
Unable to decode Packages/Meetio/assets/default/dirty_dot_icon.png
Unable to decode Packages/Meetio/assets/default/arrow_left.png
Errors parsing theme:
  the variable "colorWhite" is not defined in Packages\Meetio Theme\Meetio.json:790:28
  must be a vector or a map with a "rules" key in Packages\Meetio Theme\Meetio.sublime-theme:1:1
Errors parsing theme:
  the variable "colorWhite" is not defined in Packages\Meetio Theme\Meetio.json:790:28
  must be a vector or a map with a "rules" key in Packages\Meetio Theme\Meetio.sublime-theme:1:1
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/SolarizedToggle.sublime-settings
"Packages/Color Scheme - Default/Solarized (Dark).tmTheme" is no longer maintained and is now part of "Color Scheme - Legacy"
Errors parsing theme:
  the variable "colorWhite" is not defined in Packages\Meetio Theme\Meetio.json:790:28
  must be a vector or a map with a "rules" key in Packages\Meetio Theme\Meetio.sublime-theme:1:1
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/SolarizedToggle.sublime-settings
Errors parsing theme:
  the variable "colorWhite" is not defined in Packages\Meetio Theme\Meetio.json:790:28
  must be a vector or a map with a "rules" key in Packages\Meetio Theme\Meetio.sublime-theme:1:1
reloading settings Packages/User/Preferences.sublime-settings

**Any help is appreciated... Really love Meetio theme since it was published first time!**

**Comment by f8ttyc8t** [comment]
Btw.: extracting ressouces (png files) using e.g. 7zip works, icons are white & transparent (see attached file).

![arrow_folder_open@3x](https://user-images.githubusercontent.com/1023438/67566865-0ae4d700-f729-11e9-8196-c9bb97c400fa.png)

**Comment by mauroreisvieira** [comment]
Hi @f8ttyc8t I will launch the version 3.0.0 today, and I guess will be fix the path issues.

**Comment by f8ttyc8t** [comment]
Great to hear! Looking forward to using it.

~~Btw.: problem mentioned seems to occur only on some (Windows-) installations.~~
(happens on other Windows machines too)

**Comment by f8ttyc8t** [comment]
@mauroreisvieira - Using 3.0.2 on my Mac still causes problems (not checked on Windows yet).
Errors have changed, but are similar (only related to theme, not to color scheme which works well in my case):

Unable to decode Packages/Meetio-Theme/assets/arrow_left.png
Unable to decode Packages/Meetio-Theme/assets/vsc_untracked.png
Unable to decode Packages/Meetio-Theme/assets/vsc_modified.png
Unable to decode Packages/Meetio-Theme/assets/vsc_added.png
Unable to decode Packages/Meetio-Theme/assets/vsc_staged.png
Errors parsing theme:
  must be a vector or a map with a "rules" key in Packages/Meetio Theme/Meetio-Theme.sublime-theme:1:1
reloading settings Packages/User/Preferences.sublime-settings



Anything I need to do to bring it to work?

**Comment by f8ttyc8t** [comment]
Think it might be related to using "Meetio Theme" vs "Meetio-Theme" as sub-part of path.
ST tries to open files based on folder "Meetio-Theme" where they are probably stored in "Meetio Theme" related folder (see attached screenshot, file vcs_modified.png)

Hope I could be of help...

<img width="1294" alt="Screenshot 2019-10-26 at 10 42 29" src="https://user-images.githubusercontent.com/1023438/67616822-81431100-f7dd-11e9-94fa-6af11881a573.png">

**Comment by mauroreisvieira** [comment]
Hi @f8ttyc8t thanks a lot for you help. I forgot the rename the path for images with out "-".

I guess now is fixed on version 3.0.3.

**Comment by f8ttyc8t** [comment]
@mauroreisvieira Works like a charm now - thank you very much for sharing your work with community!

(btw. helping you sorting out glitches is the least I can do)

**Comment by mauroreisvieira** [comment]
Hi @f8ttyc8t it's a big help. Thanks for your feedback and for use Meetio.
