### ISSUE TITLE
Settings and Theme Configuration

### ISSUE THREAD

**Issue by zpreston123** [meetio-theme/sublime-meetio-theme#26]
Entered "Meetio: Edit Settings" and got the following error:
<img width="1280" alt="Screen Shot 2019-10-26 at 8 03 53 AM" src="https://user-images.githubusercontent.com/11165740/67619265-6a91bf80-f7c7-11e9-864e-4610deddddf3.png">

Also entered "Meetio: Theme Configuration" and got the following error:
<img width="1280" alt="Screen Shot 2019-10-26 at 8 04 04 AM" src="https://user-images.githubusercontent.com/11165740/67619278-8c8b4200-f7c7-11e9-8841-cffe5b1f08d3.png">

I can access the Settings via Preferences -> Package Settings -> Meetio Theme -> Edit Settings.
However, I cannot access the theme configuration via Preferences -> Package Settings -> Meetio Theme -> Theme Configuration:
<img width="1280" alt="Screen Shot 2019-10-26 at 8 16 58 AM" src="https://user-images.githubusercontent.com/11165740/67619377-066ffb00-f7c9-11e9-9439-77d46e84e6db.png">

Using Sublime Text (Version 3.2.2, Build 3211) on macOS Catalina (Version 10.15).

**Comment by mauroreisvieira** [comment]
Hi @zpreston123 TY for report I'm work on this.

Sorry for that.

**Comment by zpreston123** [comment]
Just got the updated theme.
The commands work except the Theme Configuration option in the file menu.

**Comment by mauroreisvieira** [comment]
Hi @zpreston123 thanks for your report, fixed in new version.

**Comment by zpreston123** [comment]
Great, it works!  Thank you.
