### ISSUE TITLE
Errors parsing theme:   must be a vector or a map with a "rules" key in Packages/Meetio Theme/Meetio-Theme.sublime-theme:1:1

### ISSUE THREAD

**Issue by TerminalFi** [meetio-theme/sublime-meetio-theme#29]
I have the latest release from PackageControl and on startup, the console shows the following error

`Errors parsing theme:
  must be a vector or a map with a "rules" key in Packages/Meetio Theme/Meetio-Theme.sublime-theme:1:1`

ST version: 4067 osx x64 channel: dev

**Comment by mauroreisvieira** [comment]
Hi @TheSecEng I can't reproduce that issue, since my theme is installed directly from Github, but I will install Meetio Theme in other machine via Package Control to test.

Thanks for your report!

**Comment by TerminalFi** [comment]
Very interesting, let me try updating to the latest commits vs PC and see if it is resolved.

**Update**: Yes, even after fully removing Meetio then doing a git clone and moving it accordingly, that message persists

**Comment by mauroreisvieira** [comment]
it is likely that the error in the theme comes from the fact that Meetio Theme is extending a JSON file.

But I will test.

**Comment by mauroreisvieira** [comment]
Hi @TheSecEng  sorry for the delay. 
Please check if it's fixed on new version.

**Comment by TerminalFi** [comment]
> Hi @TheSecEng sorry for the delay.
> Please check if it's fixed on new version.

Hey @mauroreisvieira the problem persists. I will do a clean install of Sublime and validate to rule out my environment.

**Comment by TerminalFi** [comment]
> Hi @TheSecEng sorry for the delay.
> Please check if it's fixed on new version.

A full, fresh install of sublime and reconfiguration resolved this issue. Sorry for the confusion. Not sure what package was conflicting.
