### ISSUE TITLE
React JS Syntax Highlighting Missing

### ISSUE THREAD

**Issue by zpreston123** [meetio-theme/sublime-meetio-theme#33]
Theme appears to be missing React JS syntax highlighting.

Here's an example screenshot:
<img width="1280" alt="Screen Shot 2020-03-25 at 9 51 47 PM" src="https://user-images.githubusercontent.com/11165740/77602079-e614ab80-6ee2-11ea-8ca9-977c22c357d4.png">

Example code is from https://www.w3schools.com/REACT/default.asp.

**Comment by mauroreisvieira** [comment]
It's required install the Babel package to resolve this issue.

**Comment by zpreston123** [comment]
Installed the Babel package and switched to JavaScript (Babel) syntax.

Here's a screenshot with same example code as above:
<img width="1280" alt="Screen Shot 2020-03-29 at 9 48 21 AM" src="https://user-images.githubusercontent.com/11165740/77850778-af6cb880-71a2-11ea-8eb9-20dd958ec97e.png">

Here are a few more example screenshots:
<img width="1280" alt="Screen Shot 2020-03-29 at 9 56 59 AM" src="https://user-images.githubusercontent.com/11165740/77850919-bc3ddc00-71a3-11ea-8133-a892f4f78efd.png">
<img width="1280" alt="Screen Shot 2020-03-29 at 10 09 01 AM" src="https://user-images.githubusercontent.com/11165740/77851136-5a7e7180-71a5-11ea-8e54-81719bab4948.png">
https://www.w3schools.com/REACT/react_forms.asp

<img width="1280" alt="Screen Shot 2020-03-29 at 10 07 29 AM" src="https://user-images.githubusercontent.com/11165740/77851111-1c814d80-71a5-11ea-975f-e6e4e98eebe8.png">
https://www.w3schools.com/REACT/react_components.asp

**Comment by mauroreisvieira** [comment]
This issue will be solved on version 4.0.0.

Thanks for you report.

**Comment by mauroreisvieira** [comment]
Version 4.0.0 is out!
