### ISSUE TITLE
Python highlight issue with function as parameter

### ISSUE THREAD

**Issue by TerminalFi** [meetio-theme/sublime-meetio-theme#34]
**Issue** 
When commands are passed as parameters some of the highlighting is missing or incorrect.

See `str()`

<img width="403" alt="image" src="https://user-images.githubusercontent.com/32599364/78036546-6cdce480-7338-11ea-9900-cc54f2aa4b02.png">

**Comment by mauroreisvieira** [comment]
Hi @TheSecEng, is strange because now I don't specify the scopes for specific language, so it's should work. But I will check.
