### ISSUE TITLE
Git Syntax Support

### ISSUE THREAD

**Issue by TerminalFi** [meetio-theme/sublime-meetio-theme#35]
**Is your feature request related to a problem? Please describe.**
With git going hand and hand with development, we should support git syntax.

**Describe the solution you'd like**
Add git syntax scopes to being colored.

Git Scopes can be found in the Git Formats package that ships with Sublime Merge

**Comment by mauroreisvieira** [comment]
Hi @TheSecEng I not understand the issue, can you send me some link with git scopes, and provide some screen shoot of the issue?

**Comment by TerminalFi** [comment]
https://github.com/sublimehq/Packages/tree/master/Git%20Formats

This is a default package with ST

**Comment by mauroreisvieira** [comment]
Thanks for your report. It's fixed on v4.1.0!

<img width="620" alt="Screenshot 2020-04-03 at 23 42 28" src="https://user-images.githubusercontent.com/3084774/78410653-e14ba800-7604-11ea-8a10-5df902ec6a04.png">
