### ISSUE TITLE
Incorrect class name

### ISSUE THREAD

**Issue by TerminalFi** [meetio-theme/sublime-meetio-theme#36]
I will submit a PR tonight if @mauroreisvieira doesn't beat me to fixing it.

**What**
In the find bar, the in selection icon is missing the hover attribute. This is due to an incorrect class name. See below.
`in_selection` should be `icon_in_selection`
https://github.com/meetio-theme/sublime-meetio-theme/blob/cd8a0450a5173fb7f2bba0f84460c96f9fa301da/scripts/theme/files/buttons.json#L114-L118

**Revised Rule**
```
        {
            "class": "icon_in_selection",
            "attributes": [
                "hover"
            ],
            "layer0.opacity": {
                "target": 0.9,
                "speed": 5,
                "interpolation": "smoothstep"
            }
        },
```

**Comment by mauroreisvieira** [comment]
Hi @TheSecEng thanks for you catch, please make a PR I will accept.
