### ISSUE TITLE
Comment Scoping

### ISSUE THREAD

**Issue by TerminalFi** [meetio-theme/sublime-meetio-theme#40]
**Describe the bug**
Some syntax definitions fail to define comments on a `comment.line` or `comment.block` level, should we support `comment` as well, since more specifics will match, this wont impact `line` or `block`

**To Reproduce**
1. Install Dockerfile (Syntax) from PC
2. Insert a Comment. The `#` will be colored correctly while the actual comment will be colored differently.

**Expected behavior**
The entire comment should have the correct syntax color

**Screenshots**

![image](https://user-images.githubusercontent.com/32599364/81578437-ce04c880-9378-11ea-9316-3be8459044fe.png)

https://github.com/meetio-theme/sublime-meetio-theme/blob/5acd180e0fec9cf2f0d2d20d45693b343f5ce126/schemes/Meetio-Theme-Dark.sublime-color-scheme#L62

https://github.com/meetio-theme/sublime-meetio-theme/blob/5acd180e0fec9cf2f0d2d20d45693b343f5ce126/schemes/Meetio-Theme-Light.sublime-color-scheme#L62

**Fix**
```json
{
    "name": "COMMENTS - Single and multi-line comments should use, respectively",
    "scope": "comment,comment.line,comment.block",
    "foreground": "var(comments)",
    "font_style": "italic"
},
```

**Comment by TerminalFi** [comment]
@mauroreisvieira should this be something we include? Or should we open issues on the syntax repo's to better scope their comments

**Comment by mauroreisvieira** [comment]
Hi @TheSecEng I guess you can go with your fix approach:

```
{
    "name": "COMMENTS - Single and multi-line comments should use, respectively",
    "scope": "comment,comment.line,comment.block",
    "foreground": "var(comments)",
    "font_style": "italic"
}
```

because with this, we can coverage other cases.
