### ISSUE TITLE
Invalid Property

### ISSUE THREAD

**Issue by TerminalFi** [meetio-theme/sublime-meetio-theme#42]
**Describe the bug**
The property `font.italic` is not valid on `quick_panel_path_label`

**To Reproduce**
1. Go to LSP Document Symbols

```diff
{
     "class": "quick_panel_path_label",
     "font.face": "var(fontFace)",
     "font.size": "var(panelPathRowFontSize)",
-    "font.italic": "var(panelPathRowFontItalic)",
     "fg": "var(panelPathRowColor)",
     "match_fg": "var(panelRowMatchColor)",
     "selected_fg": "var(panelRowSelectedColor)",
     "selected_match_fg": "var(panelRowSelectedMatchColor)"
}
```

`no such prop font.italic when matching quick_panel_path_label against quick_panel_path_label`

**Comment by mauroreisvieira** [comment]
Hi @TheSecEng thanks for report.

**Comment by TerminalFi** [comment]
@mauroreisvieira I am fixing it now and will push a PR

**Comment by mauroreisvieira** [comment]
Thanks so much @TheSecEng.
