### ISSUE TITLE
Find in Files result file name color missing

### ISSUE THREAD

**Issue by willrowe** [meetio-theme/sublime-meetio-theme#43]
**Describe the bug**
When running Find in Files, the results does not color the file name. It ends up being white, which is the same color as the code context itself, making it very difficult to see when you have scrolled into a new file.

**To Reproduce**
1. Run Find in Files.
2. See the results.

**Expected behavior**
The file name should have a different color than the rest of the text.

**Additional Information**
The scopes for the file name line are:
- text.find-in-files
- entity.name.filename.find-in-files

**Comment by TerminalFi** [comment]
Thanks for the feedback. We will have a fix for this in the next release

**Comment by TerminalFi** [comment]
@willrowe a new package has been release so running `Package Control: Upgrade Package` should allow you to pull the latest

**Comment by willrowe** [comment]
Great, thank you so much!
