### ISSUE TITLE
Missing Control: sidebar_button_control

### ISSUE THREAD

**Issue by TerminalFi** [meetio-theme/sublime-meetio-theme#47]
**Describe the bug**
Currently missing the `sidebar_button_control` which is what is displayed in the lower right hand corner.

**Issue**
![image](https://user-images.githubusercontent.com/32599364/114219796-fcd84580-991f-11eb-84ff-501aa5d0ec75.png)

**Resolved Appearance**
![image](https://user-images.githubusercontent.com/32599364/114219882-1ed1c800-9920-11eb-82a7-3a27ac52268e.png)

**Comment by mauroreisvieira** [comment]
Hey @TheSecEng thanks, I will fix that ASAP.

**Comment by TerminalFi** [comment]
Unable to reproduce
