### ISSUE TITLE
Configuration Settings Disappeared

### ISSUE THREAD

**Issue by zpreston123** [meetio-theme/sublime-meetio-theme#51]
**Describe the bug**
When opening the Default Configuration, existing settings prior to the update are no longer shown.

**To Reproduce**
1. Open command palette.
2. Enter "Meetio Theme: Default Configuration".
3. Results are shown with empty "variables" object.

**Expected behavior**
Existing settings would appear in Default Configuration.

**Screenshots**
<img width="1280" alt="Screen Shot 2021-05-28 at 12 54 26 PM" src="https://user-images.githubusercontent.com/11165740/120042586-5ed83180-bfd8-11eb-91df-6b4f0b98d3f4.png">

**Comment by mauroreisvieira** [comment]
Hey @zpreston123 thanks for your feedback.

That is not an issue, the problem is, now the name has changed from `Meetio-Theme` to `Meetio Theme` and will lose old customizations since the path are different.

**Comment by zpreston123** [comment]
OK, is the issue resolvable so the old configuration settings are restored?

**Comment by zpreston123** [comment]
@mauroreisvieira Found the old configuration file in the User directory, then copied and pasted the settings into the new configuration file.

Would it be possible to fix the theme, so the next version would handle the transfer automatically?

**Comment by mauroreisvieira** [comment]
Hey, @zpreston123 it's a good question, I need to investigate a bit.

@TheSecEng do you have any idea if it's is possible?

**Comment by TerminalFi** [comment]
Sorry for the delay. This would only be an issue if we change the name again. @mauroreisvieira do we plan on changing the actual name of the themes anymore? If not, than this can be closed.

If so, we can just add some logic into our python code for this.

**Comment by mauroreisvieira** [comment]
Hey @TheSecEng nop, that will be the final name for Meetio.
