### ISSUE TITLE
Old Asset being Used

### ISSUE THREAD

**Issue by TerminalFi** [meetio-theme/sublime-meetio-theme#54]
**Describe the bug**
An old asset from the Default theme is being used

**To Reproduce**
1. Open Sublime
2. View Console

**Expected behavior**
No error

`'Theme - Default/common/dark/tab_dirty.png'` is not longer valid and should be `'Theme - Default/common/tab_dirty.png'`

**Comment by mauroreisvieira** [comment]
Hey, thanks for report
