### ISSUE TITLE
Search icon not showing in quick panel

### ISSUE THREAD

**Issue by arturomartin** [meetio-theme/sublime-meetio-theme#55]
The search icon does not show in quick panel although the setting is set to true: `"meetio_input_search_icon": true`

**Screenshot:**
<img width="688" alt="Screenshot on 2021-06-24 at 11-25-03" src="https://user-images.githubusercontent.com/234412/123249153-95727080-d4e0-11eb-928a-5c0fecd6fb6f.png">

**Comment by mauroreisvieira** [comment]
Hey @arturomartin, can you tell me what version of Sublime Text we are using and the OS?

**Comment by arturomartin** [comment]
Of course, @mauroreisvieira 
- Sublime Text 4, Dev Channel, **Build 4109**
- macOS Big Sur, **11.4**

**Comment by mauroreisvieira** [comment]
Hey, @arturomartin please check if the new version solves that issue.

**Comment by arturomartin** [comment]
Sorry for the late answer, @mauroreisvieira 

No, it doesn't seem it solved it :(

<img width="760" alt="Screenshot on 2021-06-28 at 09-37-00" src="https://user-images.githubusercontent.com/234412/123606110-7895b000-d7f4-11eb-9cc6-21b6ff212c4e.png">

**Comment by mauroreisvieira** [comment]
Hum, very strange, can you please remove that `"meetio_input_search_icon"` from your settings? By default, the icon should appear.

**Comment by arturomartin** [comment]
I just did it and it's still not showing up. I even deleted all my settings (both of Meetio and Sublime Text) just to see if there was something causing it but no luck…

**Comment by mauroreisvieira** [comment]
Can you please remove the Meetio Theme and install it again? 

It seems that the icon is rendered, but without any color.

**Comment by arturomartin** [comment]
<img width="1013" alt="Screenshot on 2021-06-28 at 11-15-46" src="https://user-images.githubusercontent.com/234412/123620783-7df9f700-d802-11eb-9a86-c5c88ba1c7a4.png">

After reinstalling, at first it seems the search icon is disabled by default, as you can see in the screenshot. If I try to enable it, the result is the same as in the previous screenshots.

**Comment by mauroreisvieira** [comment]
If you change between `Meetio Theme` and `Meetio Theme High Contrast` the result is the same?

Can you please, open the console and check if exists any error?

**Comment by arturomartin** [comment]
Yes, the result is the same.

The console doesn't show any kind of error, it just prints `reloading settings Packages/User/Preferences.sublime-settings`.

Maybe there's something wrong with the image itself? Don't think so, as I checked it in the package and it seems to be fine, but I'm running out of ideas :P

**Comment by arturomartin** [comment]
Mmm, sorry, my bad, I just found this in the console, but maybe it was when deleting and reinstalling the theme?:

```
unloading python 3.3 plugin Meetio Theme.customization
unloading python 3.3 plugin Meetio Theme.Icons
reloading settings Packages/Meetio Theme/Preferences.sublime-settings
ignored packages updated to: ["Meetio Theme", "Vintage"]
unloading python 3.3 plugin Meetio Theme.customization
unloading python 3.3 plugin Meetio Theme.Icons
reloading settings Packages/Meetio Theme/Preferences.sublime-settings
Unable to decode Packages/Meetio Theme/textures/spinner.png
Unable to decode Packages/Meetio Theme/textures/spinner1.png
Unable to decode Packages/Meetio Theme/textures/spinner10.png
Unable to decode Packages/Meetio Theme/textures/spinner11.png
Unable to decode Packages/Meetio Theme/textures/spinner2.png
Unable to decode Packages/Meetio Theme/textures/spinner3.png
Unable to decode Packages/Meetio Theme/textures/spinner4.png
Unable to decode Packages/Meetio Theme/textures/spinner5.png
Unable to decode Packages/Meetio Theme/textures/spinner6.png
Unable to decode Packages/Meetio Theme/textures/spinner7.png
Unable to decode Packages/Meetio Theme/textures/spinner8.png
Unable to decode Packages/Meetio Theme/textures/spinner9.png
Unable to decode Packages/Meetio Theme/textures/actions/branch.png
Unable to decode Packages/Meetio Theme/textures/actions/close.png
Unable to decode Packages/Meetio Theme/textures/actions/history.png
Unable to decode Packages/Meetio Theme/textures/actions/more.png
Unable to decode Packages/Meetio Theme/textures/actions/sidebar.png
Unable to decode Packages/Meetio Theme/textures/find/case_sensitive.png
Unable to decode Packages/Meetio Theme/textures/find/highlight_matches.png
Unable to decode Packages/Meetio Theme/textures/find/in_context.png
Unable to decode Packages/Meetio Theme/textures/find/in_selection.png
Unable to decode Packages/Meetio Theme/textures/find/preserve_case.png
Unable to decode Packages/Meetio Theme/textures/find/regex.png
Unable to decode Packages/Meetio Theme/textures/find/use_buffer.png
Unable to decode Packages/Meetio Theme/textures/find/use_gitignore.png
Unable to decode Packages/Meetio Theme/textures/find/whole_word.png
Unable to decode Packages/Meetio Theme/textures/find/wrap.png
Unable to decode Packages/Meetio Theme/textures/input/search.png
Unable to decode Packages/Meetio Theme/textures/navigation/arrow_down.png
Unable to decode Packages/Meetio Theme/textures/navigation/arrow_left_small.png
Unable to decode Packages/Meetio Theme/textures/navigation/arrow_right.png
Unable to decode Packages/Meetio Theme/textures/navigation/arrow_right_small.png
Unable to decode Packages/Meetio Theme/textures/overlay/background.png
Unable to decode Packages/Meetio Theme/textures/overlay/border.png
Unable to decode Packages/Meetio Theme/textures/overlay/shadow.png
Unable to decode Packages/Meetio Theme/textures/tab/dirty_dot.png
Unable to decode Packages/Meetio Theme/textures/tab/dirty_pencil.png
Unable to decode Packages/Meetio Theme/textures/tree/disclosure_collapsed.png
Unable to decode Packages/Meetio Theme/textures/tree/disclosure_expanded.png
Unable to decode Packages/Meetio Theme/textures/tree/folder_closed.png
Unable to decode Packages/Meetio Theme/textures/tree/folder_dup.png
Unable to decode Packages/Meetio Theme/textures/tree/folder_open.png
Unable to decode Packages/Meetio Theme/textures/vcs/vcs_added.png
Unable to decode Packages/Meetio Theme/textures/vcs/vcs_modified.png
Unable to decode Packages/Meetio Theme/textures/vcs/vcs_staged.png
Unable to decode Packages/Meetio Theme/textures/vcs/vcs_untracked.png
```

**Edit:**

Just unistalled and reinstalled it again and those errors are not showing anymore in the console:

```
Package Control: The package Meetio Theme has been removed
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["CSS", "Vintage"]
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
ignored packages updated to: ["CSS", "Meetio Theme", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["CSS", "Vintage"]
reloading settings Packages/Meetio Theme/Preferences.sublime-settings
reloading python 3.3 plugin Meetio Theme.customization
reloading python 3.3 plugin Meetio Theme.Icons
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

**Comment by mauroreisvieira** [comment]
Ok, let's try that:

- Install [PackageDev](https://packagecontrol.io/packages/PackageDev).
- Go to command palette type: "PakageDev: Edit Current Theme" 
- Paste the following snippet:

```json
{
    "variables": {},
    "rules": [
         {
            "class": "text_line_control",
            "parents": [
                {
                    "class": "overlay_control"
                }
            ],
            "layer1.opacity": 0,
            "layer2.inner_margin": [
                52,
                48,
                0,
                0
            ],
            "layer2.draw_center": false,
            "layer2.texture": "Meetio Theme/textures/input/search.png",
            "layer2.tint": "#f00",
            "layer2.opacity": 1,
            "content_margin": [
                52,
                10,
                10,
                10
            ],
            "settings": [
                "meetio_input_search_icon"
            ]
        },
    ],
}
```

The result: 

<img width="1715" alt="Screenshot 2021-06-28 at 11 45 40 AM" src="https://user-images.githubusercontent.com/3084774/123624398-6a508f80-d806-11eb-995a-8e6cff7033e5.png">

**Comment by arturomartin** [comment]
I did that a few days ago, trying to force a color on that icon but no luck. I did it again now using just your snippet and PackageDev. No luck. It makes no sense…

<img width="1783" alt="Screenshot on 2021-06-28 at 11-51-27" src="https://user-images.githubusercontent.com/234412/123625212-712bd200-d807-11eb-94dd-572f03b48c88.png">

**Comment by mauroreisvieira** [comment]
Hey, can you pelase test to add that options in your settings:

```json
"line_padding_bottom": 12,
"line_padding_top": 12,
```

**Comment by arturomartin** [comment]
I think you found it… Any value below 5 makes the icon disappear.

<img width="895" alt="Screenshot on 2021-06-28 at 12-03-00" src="https://user-images.githubusercontent.com/234412/123626550-df24c900-d808-11eb-8f60-f70570c60bf4.png">

**Comment by mauroreisvieira** [comment]
That blows my mind. 

If the value of line padding is smaller than 5 the icon disappears. 
I will try to understand the problem.

Thanks for the report and the help to find the issue. 

I will warn you when that issue was solved.

**Comment by arturomartin** [comment]
No, thanks to you @mauroreisvieira
Meetio is the best and most versatile theme I've used in a long time :)

**Comment by mauroreisvieira** [comment]
Thank you so much for your words. 🙏🏻

Any suggestion to improve it's welcome.

**Comment by mauroreisvieira** [comment]
Hey, @arturomartin issue solved.
Against thanks for your report.

**Comment by arturomartin** [comment]
That was fast! Thanks a lot!
