### ISSUE TITLE
Maximize /minimize window buttons are invisible

### ISSUE THREAD

**Issue by jfcherng** [meetio-theme/sublime-meetio-theme#56]
**Describe the bug**
Maximize /minimize window button is invisible on Win10 21H1.

**To Reproduce**
1. Use `Meetio Theme.sublime-theme`
2. Use *any* light color scheme, such as `Meetio Lighter.sublime-color-scheme` 
3. You can't see the maximize window and minimize window buttons.

**Expected behavior**

Maximize window and minimize window buttons should be visible.

**Screenshots**

There should be 3 buttons: max window, min window, close window.
They are there but just kind of pure white hence invisible.

![image](https://user-images.githubusercontent.com/6594915/125916244-aeeb3131-962b-4d9d-802f-08d52f31cff0.png)

**Comment by mauroreisvieira** [comment]
Hey @jfcherng thanks for your report, I check that ASAP.

**Comment by zpreston123** [comment]
Any status on this bug?

**Comment by mauroreisvieira** [comment]
Hey, @zpreston123 sorry for the delay. It's fixed in the new version.

Thanks.
