### ISSUE TITLE
Can you support using the active command to enable this theme?

### ISSUE THREAD

**Issue by jingyuexing** [meetio-theme/sublime-meetio-theme#58]
**Is your feature request related to a problem? Please describe.**
I want to use the active command to enable meetio, but look like not support
![image](https://user-images.githubusercontent.com/19589872/139600400-b6bc2a7e-4129-4788-99ba-fdf47de5bde9.png)
![image](https://user-images.githubusercontent.com/19589872/139600419-540bb65a-d7d9-4c24-8a7e-d6223008376e.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mauroreisvieira** [comment]
Hey @jingyuexing.

That option was removed from Meetio, since ST already supports a `Select Scheme` and `Select Theme`from Command Pallete.

<img width="620" alt="Screenshot 2021-11-02 at 10 38 55 AM" src="https://user-images.githubusercontent.com/3084774/139831515-3f3b389b-b977-474a-b843-0aeb1b58fe4b.png">

**Comment by jingyuexing** [comment]
> Hey @jingyuexing.
> 
> That option was removed from Meetio, since ST already supports a `Select Scheme` and `Select Theme`from Command Pallete.
> 
> <img alt="Screenshot 2021-11-02 at 10 38 55 AM" width="620" src="https://user-images.githubusercontent.com/3084774/139831515-3f3b389b-b977-474a-b843-0aeb1b58fe4b.png">

thanks for the answer.

**Comment by jingyuexing** [comment]
> Hey @jingyuexing.
> 
> That option was removed from Meetio, since ST already supports a `Select Scheme` and `Select Theme`from Command Pallete.
> 
> <img alt="Screenshot 2021-11-02 at 10 38 55 AM" width="620" src="https://user-images.githubusercontent.com/3084774/139831515-3f3b389b-b977-474a-b843-0aeb1b58fe4b.png">

By the way, this project is funky
