### ISSUE TITLE
close/dirty icons and user show_tab_close_buttons preference

### ISSUE THREAD

**Issue by abathur** [meetio-theme/sublime-meetio-theme#6]
Promising theme. Thanks for investing the time in it.

I was a little confused by the dirty icons at first, since I have `show_tab_close_buttons` set to `false` (mostly because I tend to use quite a few tabs, and in aggregate the icons can consume a lot of space).

Is it possible to just use the accent color on the tab label when a tab is dirty and `show_tab_close_buttons` is disabled?

**Comment by mauroreisvieira** [comment]
HI @abathur thanks for you feedback, I will check this possibility.

**Comment by abathur** [comment]
I guess technically it should only work that way if `highlight_modified_tabs` is also `true` :)

**Comment by mauroreisvieira** [comment]
Meetio 1.7.0 its out! 🎉

Check the new's features.
