### ISSUE TITLE
customization/spacing around inputs

### ISSUE THREAD

**Issue by abathur** [meetio-theme/sublime-meetio-theme#7]
I was looking for various parameters to tweak to see if I could cut down on the size of the find panel (and, for that matter, the console) and found some of the options/effects a little counter-intuitive. For context, I'm trying to cut it down to something a little more like the fairly tight find panel in Lyte: [
![image](https://user-images.githubusercontent.com/2548365/54005390-df23cb00-411e-11e9-9a16-2aeed51cf53d.png)
](url)

While poking at this, neither the colors or spacing behaved as expected (I'm not very familiar with sublime's theme concepts--I realize they may be a big underlying cause here.) I expected setting an input background color to change the color of the input element itself, but instead, it changes a color around the input elements:

<img width="970" alt="screen shot 2019-03-07 at 9 12 19 pm" src="https://user-images.githubusercontent.com/2548365/54005459-227e3980-411f-11e9-90b3-7c668ef37494.png">
I was also a little confused by this being the behavior with a border of 0 on the input (because this looks like a border, on the input), so I decided to go set one to see what would happen. My expectation was a narrow 4px border around the input element itself, but instead I get:
<img width="970" alt="screen shot 2019-03-07 at 9 13 19 pm" src="https://user-images.githubusercontent.com/2548365/54005465-290cb100-411f-11e9-9333-ef39e4eeebe3.png">
So it looks like the border of 4 is on the inside of the containing element. I confirm what I'm seeing by changing the border color to match the background color:
<img width="970" alt="screen shot 2019-03-07 at 9 14 02 pm" src="https://user-images.githubusercontent.com/2548365/54005470-2c07a180-411f-11e9-9b0e-2ac30f0357d7.png">
Next I decided to try shrinking down the size of the panel. I changed the height on the minimum button size, but only a few elements shrink, so it doesn't actually give me much real control over the size of the whole panel:
<img width="850" alt="screen shot 2019-03-07 at 9 17 41 pm" src="https://user-images.githubusercontent.com/2548365/54005471-2f9b2880-411f-11e9-978e-90a56866a142.png">
Out of curiosity I took a peek at the console, but this is pretty rough when the input and border/background aren't the same color:
<img width="970" alt="screen shot 2019-03-07 at 9 19 58 pm" src="https://user-images.githubusercontent.com/2548365/54005474-34f87300-411f-11e9-9c54-d08f9644bedb.png">

**Comment by mauroreisvieira** [comment]
I guess this problem is solved with new version. I'm waiting for you feedback to close this issue.

**Comment by abathur** [comment]
This fixes the border-color issue: <img width="905" alt="Screen Shot 2019-03-13 at 9 07 16 AM" src="https://user-images.githubusercontent.com/2548365/54285543-2de2c200-4570-11e9-8e65-a24b19ef3724.png">

My comments on adjusting the size of the find panel are still relevant, but I can open a separate issue for that if you like.

I also noticed something a little odd while playing with the border size (this may just be how ST3 handles the border--I haven't tried customizing this in any other theme before). It behaves as expected at border size 4:
<img width="905" alt="Screen Shot 2019-03-13 at 9 11 16 AM" src="https://user-images.githubusercontent.com/2548365/54293855-b36d6e80-457e-11e9-991c-fbe01c3ec533.png">
And as expected at size 1:
<img width="905" alt="Screen Shot 2019-03-13 at 9 11 27 AM" src="https://user-images.githubusercontent.com/2548365/54293856-b36d6e80-457e-11e9-9488-c66d8f10c423.png">
But it looks like size 0 sets it to default:
<img width="905" alt="Screen Shot 2019-03-13 at 10 55 52 AM" src="https://user-images.githubusercontent.com/2548365/54293858-b4060500-457e-11e9-8200-49251e969527.png">

It looks like the border can still be forced not to show with a small size like `0.1`:
<img width="905" alt="Screen Shot 2019-03-13 at 11 04 04 AM" src="https://user-images.githubusercontent.com/2548365/54294858-f5e37b00-457f-11e9-903d-94b960ecfd02.png">

**Comment by mauroreisvieira** [comment]
@abathur It is not possible to define border in the Sublime. What I actually do is create a layer with a background, and then I change the margin of this container to look like a border. :(

**Comment by abathur** [comment]
Playing with the input background color some more shows that I wasn't quite understanding everything going on. It looks like any pure background color obscures some blending or alpha within the input. Here's the input background at 1.0 and again at 0:

<img width="905" alt="Screen Shot 2019-03-13 at 11 27 00 AM" src="https://user-images.githubusercontent.com/2548365/54296723-6f309d00-4583-11e9-8e2a-a836375f50d1.png">
<img width="905" alt="Screen Shot 2019-03-13 at 11 28 08 AM" src="https://user-images.githubusercontent.com/2548365/54296732-7192f700-4583-11e9-9f26-2431d8383abb.png">

Edit: Maybe this illustrates why the above is a little confusing better. Below the input_background_color and panel_control_background_color are both set to `["accent", 0.2]`, but don't look the same.

<img width="905" alt="Screen Shot 2019-03-13 at 11 35 35 AM" src="https://user-images.githubusercontent.com/2548365/54297474-f4688180-4584-11e9-9eb2-eea0620ce285.png">


(It's fine to refuse to change some of these things--I just wanted to play around with the theme to see if it could do what I wanted, and saw some things that were a little confusing. I don't want you to have to spend a lot of time refactoring or making the theme more complex if you don't see long-term value in a specific change.)

**Comment by mauroreisvieira** [comment]
The status bar have a issue, and because of that the color appear different, I will fix this.

**Comment by mauroreisvieira** [comment]
@abathur the bug is solver. But related wirt colors of panel and status bar are differente is related in a overlapping containers. I cant't solve this :/

**Comment by abathur** [comment]
Oh--not concerned about the status bar there, sorry--just that the input panel background and the input background itself are set to the same color values but didn't have the same color.

I also noticed some color/spacing issues with the list input menus used for "goto anything", "command palette", plugin menus, and so on (let me know if you'd prefer I edit this out and move it to a new thread).

Here's a window using Lyte-dark theme, with a selection list menu open for a plugin:
<img width="905" alt="Screen Shot 2019-03-14 at 10 44 54 AM" src="https://user-images.githubusercontent.com/2548365/54371525-85a02c80-4647-11e9-8cee-097e6a5359fd.png">
Here's the same in Meetio:
<img width="905" alt="Screen Shot 2019-03-14 at 10 42 47 AM" src="https://user-images.githubusercontent.com/2548365/54371488-7620e380-4647-11e9-87dd-a96e86b7df95.png">

I was hoping to make a few changes, but I didn't see existing variables for controlling them:
- adjust background color for the selected item to make it less visually dominant against the darker background I'm using
- reduce the per-item pad/margin (at least vertically)
- adjust the background for un-selected items or the panel as a whole so that it stands out a little better from the darker background I'm using (which hides the drop-shadow that nicely distinguishes it in your schemes)

**Comment by mauroreisvieira** [comment]
Hi @abathur can you send me you Meetio Theme configurations to try in my computer and fix all issues.

**Comment by mauroreisvieira** [comment]
@abathur and @pulcinello solved in new version 1.8.0.
