### ISSUE TITLE
Any way to customize the selected bg of the command palette?

### ISSUE THREAD

**Issue by pulcinello** [meetio-theme/sublime-meetio-theme#8]
First, thanks for making this wonderful theme! I wonder if there's an option to customize the selected bg of the command palette?
![Screenshot from 2019-03-17 14 34 53](https://user-images.githubusercontent.com/3975367/54486951-74b31d80-48ca-11e9-99d0-7e2d48db35d7.png)

**Comment by mauroreisvieira** [comment]
Hi @pulcinello thanks for your feedback.
About your issue, I'm working on this this issue is always reported on #7 I hope to fix this during this week.

Thanks again.
